### ISSUE TITLE
Show Only Progressive Bar

### ISSUE THREAD

**Issue by Root-Mailer** [halilozercan/paralleldownload#11]
Hi There,

I liked your project and found very useful in my application. But i wanted to ask if i could show only the `progressive bar` (by using command line) instead of showing other options [like url , saving to , etc]. Moreover, I Am Getting This Error(Below) On Using `pget` via command line: 

Traceback (most recent call last):
  File "/home/<user>/.local/bin/pget", line 8, in <module>
    sys.exit(main())
  File "/home/<user>/.local/lib/python3.9/site-packages/pget/bin.py", line 109, in main
    run(sys.argv)
  File "/home/<user>/.local/lib/python3.9/site-packages/pget/bin.py", line 103, in run
    downloader.wait_for_finish()
  File "/home/<user>/.local/lib/python3.9/site-packages/pget/down.py", line 141, in wait_for_finish
    while self.thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

And After That, The Download Starts.

**Comment by tirkarthi** [comment]
I have created a fix in https://github.com/halilozercan/pget/pull/12 . `isAlive` was deprecated alias to `is_alive` and was removed in Python 3.9 in PR https://github.com/python/cpython/pull/15225
